### ISSUE TITLE
What about Typescript?

### ISSUE THREAD

**Issue by leandrosimoes** [edelciomolina/quibi-experience#4]
Since this project is "just for the pleasure of coding and creating things", I believe that it is a good opportunity for you, @edelciomolina, to learn new stuff, like Typescript for example!

Advantages:

* Typings! Ensure that every parameter, variable and more will be filled in with the proper type;
* Interfaces, Inheritance and almost all the OOP can provide for you;
* Learning new stuff open your mind for future projects;

Unadvantages:

* I would say NONE! But I must be honest and say that the development will get longer to finish, but, it's just a little bit, and I think that this time will worth it.

So, think about it and let me know. Just in case, I'll start to write my code in Typescript, but I can change to javascript if you ~(Do not have balls to lean Typescript)~ do not agree to use Typescript.

**Comment by edelciomolina** [comment]
🤔 Well, your Typescript challenge sounds good! 
I accept put my balls on game, but not on this project!
I propose something bigger like a Atari 2600 game, what do you think about it?

Thats is my suggestion!
**H.E.R.O** https://www.youtube.com/watch?v=1YAmdDE3ivk

We can start a new repository totally with Typescript. Take a look and thing about how we can do it, You´ll note that there is a game patern and that will propose us to have an organized code.

**Comment by leandrosimoes** [comment]
I'll think about.
